"""inventory sessions

Revision ID: 18d40c7e8d50
Revises: 8dc1f6bf903e
Create Date: 2026-07-18 07:19:13.576196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d40c7e8d50'
down_revision: Union[str, Sequence[str], None] = '8dc1f6bf903e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accuracy_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_sessions_store_id'), 'inventory_sessions', ['store_id'], unique=False)
    op.create_table('inventory_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected', sa.Integer(), nullable=False),
    sa.Column('counted', sa.Integer(), nullable=False),
    sa.Column('counted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invcount_session_product', 'inventory_counts', ['session_id', 'product_id'], unique=True)
    op.create_index(op.f('ix_inventory_counts_session_id'), 'inventory_counts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_counts_session_id'), table_name='inventory_counts')
    op.drop_index('ix_invcount_session_product', table_name='inventory_counts')
    op.drop_table('inventory_counts')
    op.drop_index(op.f('ix_inventory_sessions_store_id'), table_name='inventory_sessions')
    op.drop_table('inventory_sessions')
    # ### end Alembic commands ###
