"""normalized product fields

Revision ID: 7f44226f21cd
Revises: d332ebc27b19
Create Date: 2026-07-17 13:25:40.051488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f44226f21cd'
down_revision: Union[str, Sequence[str], None] = 'd332ebc27b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('products', sa.Column('size_value', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('size_unit', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('products', sa.Column('name_raw', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('products', sa.Column('source', sa.String(length=30), nullable=False, server_default='manual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'source')
    op.drop_column('products', 'name_raw')
    op.drop_column('products', 'size_unit')
    op.drop_column('products', 'size_value')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
