"""inventory expiry date

Revision ID: 8dc1f6bf903e
Revises: 7f44226f21cd
Create Date: 2026-07-17 14:49:23.616166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc1f6bf903e'
down_revision: Union[str, Sequence[str], None] = '7f44226f21cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_inventory_expiry_date'), 'inventory', ['expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_expiry_date'), table_name='inventory')
    op.drop_column('inventory', 'expiry_date')
    # ### end Alembic commands ###
