"""inventory min stock

Revision ID: 9b0c0ba77354
Revises: 18d40c7e8d50
Create Date: 2026-07-18 11:58:48.113344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0c0ba77354'
down_revision: Union[str, Sequence[str], None] = '18d40c7e8d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('min_stock', sa.Integer(), nullable=False,
                                         server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'min_stock')
    # ### end Alembic commands ###
